---
- name: Create directory for php-fpm
  ansible.builtin.file:
    path: /run/php
    state: directory

- name: Template php-fpm www config file
  template:
    src: /opt/manager/templates/www-config.j2
    dest: /etc/php/7.4/fpm/pool.d/www.conf
    force: yes
