---
- name: Configure nginx .conf
  template:
    src: /opt/manager/templates/nginx.j2
    dest: /etc/nginx/nginx.conf
    force: yes

- name: Configure nginx http webserver
  template:
    src: /opt/manager/templates/freepbx_http.j2
    dest: /etc/nginx/conf.d/freepbx_http.conf
    force: yes
  when: protocol == "http"

- name: Configure nginx https webserver
  template:
    src: /opt/manager/templates/freepbx_https.j2
    dest: /etc/nginx/conf.d/freepbx_https.conf
    force: yes
  when: protocol == "https"

